apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - name: nodered
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880
       